networks:
  fit3182-net:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - fit3182-net

  kafka-broker-1:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 15.135.158.73:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://15.135.158.73:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LOG_RETENTION_HOURS: 2
    networks:
      - fit3182-net

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    networks:
      - fit3182-net

  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.spark
    user: root
    environment:
      SPARK_NO_DAEMONIZE: "true"
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
      - ./:/home/student
    networks:
      - fit3182-net
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]

  pyspark-notebook:
    image: fit3182/pyspark
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/student
    environment:
      SPARK_MASTER: spark://15.135.158.73:7077
    depends_on:
      - spark-master
      - kafka-broker-1
      - mongodb
    networks:
      - fit3182-net
    command: jupyter notebook --ip=0.0.0.0 --no-browser --allow-root